# -*- coding: utf-8 -*-
"""セマンティックWeb期末.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Y-e8yY3eRx8Xyumyfe-r8_zkwknUcf-
"""

!pip install rdflib

from rdflib import Graph, Namespace, RDF, RDFS, Literal

# グラフ作成
g = Graph()

# 名前空間
EX = Namespace("http://example.org/zou/")
g.bind("ex", EX)

# クラス
g.add((EX.Egg, RDF.type, RDFS.Class))
g.add((EX.Elephant, RDF.type, RDFS.Class))
g.add((EX.Place, RDF.type, RDFS.Class))
g.add((EX.Color, RDF.type, RDFS.Class))

# プロパティ
g.add((EX.laidBy, RDF.type, RDF.Property))
g.add((EX.foundAt, RDF.type, RDF.Property))
g.add((EX.hasColor, RDF.type, RDF.Property))
g.add((EX.size, RDF.type, RDF.Property))

# インスタンス
g.add((EX.ElephantEgg1, RDF.type, EX.Egg))
g.add((EX.ElephantEgg1, EX.laidBy, EX.AfricanElephant))
g.add((EX.ElephantEgg1, EX.foundAt, EX.Savanna))
g.add((EX.ElephantEgg1, EX.hasColor, EX.Gray))
g.add((EX.ElephantEgg1, EX.size, Literal("35cm")))

g.add((EX.AfricanElephant, RDF.type, EX.Elephant))
g.add((EX.Savanna, RDF.type, EX.Place))
g.add((EX.Gray, RDF.type, EX.Color))

# 保存
g.serialize("elephant_egg.ttl", format="turtle")

print("TTLファイルを作成しました。")

print(open("elephant_egg.ttl", "r").read())

from google.colab import files
files.download("elephant_egg.ttl")